extern void scroll_castle_grounds_dl_WaterMesh_mesh_layer_5_vtx_0();
extern void scroll_castle_grounds_dl_Cylinder_005_mesh_layer_1_vtx_4();
extern void scroll_castle_grounds_dl_Cylinder_008_mesh_layer_5_vtx_0();
extern void scroll_castle_grounds_dl_Cylinder_009_mesh_layer_5_vtx_0();
extern void scroll_castle_grounds_dl_Cylinder_010_mesh_layer_5_vtx_0();
extern void scroll_castle_grounds_dl_Cylinder_015_mesh_layer_5_vtx_0();
extern void scroll_castle_grounds();
